version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestione_commesse_app
    ports:
      - "5000:5000"
    volumes:
      - gestione_commesse_data:/app/data
    restart: always

volumes:
  gestione_commesse_data:
